### ISSUE TITLE
Moon Animator not working

### ISSUE THREAD

**Issue by Vinyl789** [2garlicbread/moon-animator-2#1]
I don't know why but some days ago the plugin worked just fine, I could animate and overall it was 100% functional but now that a new update came out moon animator started to present some issues like the keyframes being invisible, my animation names being hidden and now that I tried to reinstall it, it throws an error and the button to restart studio doesn't work
the error says UI is not a valid member of plugin **"User_Init.Lua**" how can I fix this issue?

**Comment by 2garlicbread** [comment]
i'm not too sure about that error. if you could supply the full error message (preferably a screenshot), i'll get back to you regarding that.

as for the 'restart studio' button, that's standard for new installs of moon animator. although it's more of a warning message. plugins cannot restart studio, you'll need to restart it manually.

**Comment by Vinyl789** [comment]
This is what it says in the output and here is how it looks in the plugins tab

![image](https://github.com/2garlicbread/moon-animator-2/assets/172230056/37862497-dc53-461a-a31a-4b0535acfad8)

![image](https://github.com/2garlicbread/moon-animator-2/assets/172230056/2a43a4da-e2c0-46ea-8166-51604c5098ae)

**Comment by 2garlicbread** [comment]
that error seems to be unrelated to moon animator. and again, you'll need to restart studio manually to get rid of that error message.

**Comment by Vinyl789** [comment]
> that error seems to be unrelated to moon animator. and again, you'll need to restart studio manually to get rid of that error message.

it actually is a problem with the plugin because I tried removing it and this error would not pop up and only appeared once I put the plugin back in

**Comment by 2garlicbread** [comment]
i believe this may be an error on your part. did you install the plugin from the releases tab, or did you paste the `init.lua` file into your plugins folder?

**Comment by Vinyl789** [comment]
yes, every file is where it's supposed to be, even tried reinstalling roblox and nothing fixed this issue

**Comment by 2garlicbread** [comment]
could you provide me with some steps to reproduce this? i can't really solve this without seeing it myself. just explain what you did to install the plugin, maybe how you used it, etc.

**Comment by Vinyl789** [comment]
First I dowload everything and unzip it then I open roblox studio and put everything in the plugins file (again this worked before a new version of moon animator 2 came out before it started to show visual issues) tried removing it and putting it back, nothing fixed the issue

**Comment by 2garlicbread** [comment]
ah, it looks like you've installed it wrong. go to the [releases](https://github.com/2garlicbread/moon-animator-2/releases/tag/Cracked4) and install the file named 'Moon.Animator.2.rbxm' to your plugins folder.

**Comment by Vinyl789** [comment]
and where do I paste the rest of the files?

**Comment by Vinyl789** [comment]
ah, forget it I figured it out

**Comment by Vinyl789** [comment]
thanks for the help though! appreciate it :)
